jobs:
  - name: Check PR
    plan:
    - aggregate:
      - get: source
        trigger: false
    - task: Perform Test
      file: source/tasks/test.yml

resources:
  - name: source
    type: git
    source:
      uri: https://github.com/suhlig/spike-concourse-pr-check
      branch: master
