---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine/git }

inputs:
  - name: source
  - name: pull-request

run:
  path: sh
  args:
  - -ec
  - |
    cd pull-request
    echo What is the answer?
